name: Go

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      with:
        go-version: 1.20.x
      uses: actions/setup-go@v2

    - name: Run linters
      run: |
        go version
        go vet ./...
        go install honnef.co/go/tools/cmd/staticcheck@latest
        bash -c "$(go env GOPATH)/bin/staticcheck ./..."

    - name: Test
      run: go test ./...

    - name: Release
      run: |
        echo  $DOCKERHUB_TOKEN | docker login -u vingarcia --password-stdin
        docker build -t vingarcia/echoserver:latest .
        docker push vingarcia/echoserver:latest
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
